# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sample_pb2 as sample__pb2


class SampleStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SampleMethod = channel.unary_unary(
                '/Sample/SampleMethod',
                request_serializer=sample__pb2.SampleInput.SerializeToString,
                response_deserializer=sample__pb2.SampleOutput.FromString,
                )


class SampleServicer(object):
    """Missing associated documentation comment in .proto file"""

    def SampleMethod(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SampleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SampleMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.SampleMethod,
                    request_deserializer=sample__pb2.SampleInput.FromString,
                    response_serializer=sample__pb2.SampleOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Sample', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sample(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def SampleMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sample/SampleMethod',
            sample__pb2.SampleInput.SerializeToString,
            sample__pb2.SampleOutput.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
