# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0csample.proto\"\x1c\n\x0bSampleInput\x12\r\n\x05input\x18\x01 \x01(\t\"\x1e\n\x0cSampleOutput\x12\x0e\n\x06output\x18\x01 \x01(\t27\n\x06Sample\x12-\n\x0cSampleMethod\x12\x0c.SampleInput\x1a\r.SampleOutput\"\x00\x62\x06proto3'
)




_SAMPLEINPUT = _descriptor.Descriptor(
  name='SampleInput',
  full_name='SampleInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='SampleInput.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=44,
)


_SAMPLEOUTPUT = _descriptor.Descriptor(
  name='SampleOutput',
  full_name='SampleOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='SampleOutput.output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['SampleInput'] = _SAMPLEINPUT
DESCRIPTOR.message_types_by_name['SampleOutput'] = _SAMPLEOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleInput = _reflection.GeneratedProtocolMessageType('SampleInput', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEINPUT,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:SampleInput)
  })
_sym_db.RegisterMessage(SampleInput)

SampleOutput = _reflection.GeneratedProtocolMessageType('SampleOutput', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEOUTPUT,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:SampleOutput)
  })
_sym_db.RegisterMessage(SampleOutput)



_SAMPLE = _descriptor.ServiceDescriptor(
  name='Sample',
  full_name='Sample',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=78,
  serialized_end=133,
  methods=[
  _descriptor.MethodDescriptor(
    name='SampleMethod',
    full_name='Sample.SampleMethod',
    index=0,
    containing_service=None,
    input_type=_SAMPLEINPUT,
    output_type=_SAMPLEOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLE)

DESCRIPTOR.services_by_name['Sample'] = _SAMPLE

# @@protoc_insertion_point(module_scope)
